### ISSUE TITLE
[BUG]: `mlc pull` doesn't build newly added packages

### ISSUE THREAD

**Issue by SomethingGeneric** [crystal-linux/malachite#23]
### To reproduce the bug

1. Add a package to a `mlc.toml` in repo mode with pull rebuild enabled
2. run `mlc pull` 

### Expected behavior

Assuming I understand the intention of pull rebuild, it should build the newly added package, right?

**Comment by mchalunderscore** [comment]
Hi Matt, please see the top of the [README.md](https://github.com/crystal-linux/malachite#readme)

**Comment by SomethingGeneric** [comment]
Oops 😅
