### ISSUE TITLE
Automatically rebuild packages if git pulled new stuff

### ISSUE THREAD

**Issue by SomethingGeneric** [crystal-linux/malachite#5]
When using `mlc update`, it'd be cool if any repos that changed could be automatically rebuilt. Not sure if that should be a flag, or the default behavior, but it'd be helpful

**Comment by mchalunderscore** [comment]
This is actually a really good idea, I'll take a look at implementing it later

**Comment by mchalunderscore** [comment]
This is now implemented in the `development` branch! Will close when merged
